CREATE TABLE HAPPINESS (
    INDEX int NOT NULL,
    COUNTRY varchar(30) NOT NULL,
    HAPPINESS_RANK int NOT NULL,
    YEAR int NOT NULL,
    HAPPINESS_SCORE float NOT NULL,
    ECONOMY float NOT NULL,
    FAMILY float NOT NULL,
    HEALTH float NOT NULL,
    FREEDOM float NOT NULL,
    TRUST float NOT NULL,
    GENEROSITY float NOT NULL,
    PRIMARY KEY (INDEX)
    );